language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

mysql:
  database: starbug_ci
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
  - composer global require squizlabs/php_codesniffer
  - composer global require phpmd/phpmd
  - composer global require sebastian/phpcpd
  - composer global require sebastian/phploc
  - git submodule init
  - git submodule update
  - composer install
  - npm install

before_script:
  - mysql -e 'create database starbug_ci'
  - ./sb generate host
  - ./sb setup
  - ./sb migrate -t test

script: grunt ci
