language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq postfix
  - composer self-update
  - mkdir var

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
  - composer global require squizlabs/php_codesniffer
  - composer global require phpmd/phpmd
  - composer global require sebastian/phpcpd
  - phpenv rehash
  - git submodule init
  - git submodule update
  - composer install
  - npm install

before_script:
  - sudo service postfix stop
  - smtp-sink -d "%d.%H.%M.%S" localhost:2500 1000 &
  - echo -e '#!/usr/bin/env bash\nexit 0' | sudo tee /usr/sbin/sendmail
  - echo 'sendmail_path = "/usr/sbin/sendmail -t -i "' | sudo tee "/home/travis/.phpenv/versions/`php -i | grep "PHP Version" | head -n 1 | grep -o -P '\d+\.\d+\.\d+.*'`/etc/conf.d/sendmail.ini"
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot mysql
  - mysql -e 'create database starbug_ci'
  - mysql -e 'create database starbug_ci_test'
  - ./sb generate host
  - sed -i 's/"password":"test"/"password":""/' app/etc/db/default.json
  - sed -i 's/"db":"test"/"db":"starbug_ci"/' app/etc/db/default.json
  - sed -i 's/"password":"test"/"password":""/' app/etc/db/test.json
  - sed -i 's/"db":"test"/"db":"starbug_ci_test"/' app/etc/db/test.json
  - cat app/etc/db/default.json
  - cat app/etc/db/test.json
  - echo 'root' | ./sb setup
  - composer dump-autoload
  - ./sb migrate -t test
  - composer dump-autoload

script: grunt

notifications:
  email: false
