language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_install:
  - sudo apt-get update > /dev/null
  - composer self-update
  - mkdir var

install:
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql
  - composer global require squizlabs/php_codesniffer
  - composer global require phpmd/phpmd
  - composer global require sebastian/phpcpd
  - composer global require phploc/phploc
  - phpenv rehash
  - git submodule init
  - git submodule update
  - composer install
  - npm install

before_script:
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -uroot mysql
  - mysql -e 'create database starbug_ci'
  - mysql -e 'create database starbug_ci_test'
  - ./sb generate host
  - sed -i 's/"password":"test"/"password":""/' app/etc/db/default.json
  - sed -i 's/"db":"test"/"test":"starbug_ci"/' app/etc/db/default.json
  - sed -i 's/"password":"test"/"password":""/' app/etc/db/test.json
  - sed -i 's/"db":"test"/"test":"starbug_ci_test"/' app/etc/db/test.json
  - cat app/etc/db/default.json
  - cat app/etc/db/test.json
  - ./sb setup
  - ./sb migrate -t test

script: grunt ci
